
action_selector: "epsilon_greedy"
runner: "episode"

buffer_size: 10
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 15000 

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "qtran_learner"
double_q: True
mixer: "qtran_base"
mixing_embed_dim: 64
qtran_arch: "qtran_paper"
use_rnn: True
opt_loss: 1
nopt_min_loss: 0.1
rnn_hidden_dim: 128
network_size: small

name: "qtran"
use_reward_normalization: True
t_max: 180000